server:
  port: 8080

base-url:
  context: /disaster-management

alert:
  scheduler-cron: "0 */1 * * * *"
  time-window-in-mins: 10
  retention-in-days: 1

spring:
  application:
    name: alerts
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/disaster_management
    username: postgres
    password: ${DB_PASSWORD}